"""autualizacao ordem servico

Revision ID: 0c49c132f7f8
Revises: 106fc1b9597a
Create Date: 2026-08-11 22:05:48.277560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c49c132f7f8'
down_revision: Union[str, Sequence[str], None] = '106fc1b9597a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
