"""ajustar_tabela_clientes

Revision ID: 0e50ce2cabc8
Revises: fa17aaf649c8
Create Date: 2026-07-30 08:12:24.110901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e50ce2cabc8"
down_revision: Union[str, Sequence[str], None] = "fa17aaf649c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clientes", sa.Column("cpf", sa.String(length=14), nullable=False))
    op.create_index(op.f("ix_clientes_cpf"), "clientes", ["cpf"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clientes_cpf"), table_name="clientes")
    op.drop_column("clientes", "cpf")
    # ### end Alembic commands ###
