"""autualizacao ordem servico

Revision ID: 106fc1b9597a
Revises: 26a48551c78f
Create Date: 2026-08-11 21:48:31.163011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "106fc1b9597a"
down_revision: Union[str, Sequence[str], None] = "26a48551c78f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ordens_servico_visualizacao_hash_fkey"),
        "ordens_servico",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("ordens_servico_visualizacao_hash_fkey"),
        "ordens_servico",
        "usuarios",
        ["visualizacao_hash"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
