"""autualizacao ordem servico

Revision ID: 12d51f7e6718
Revises: 0c49c132f7f8
Create Date: 2026-08-11 23:13:40.398184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d51f7e6718'
down_revision: Union[str, Sequence[str], None] = '0c49c132f7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('os_itens_peca', 'quantidade',
               existing_type=sa.INTEGER(),
               comment='Quantidade física demandada do estoque',
               existing_comment='Quantidade física demandada do estoque para o carro',
               existing_nullable=False)
    op.alter_column('os_itens_peca', 'preco_unitario_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço de venda unitário congelado no momento do orçamento',
               existing_comment='Preço de venda unitário congelado no momento de fechamento do orçamento',
               existing_nullable=False)
    op.alter_column('os_itens_servico', 'preco_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço cobrado pela mão de obra no momento da execução',
               existing_comment='Preço cobrado pela mão de obra no momento da execução (preserva histórico de preços)',
               existing_nullable=False)
    op.alter_column('os_itens_servico', 'adicionado_em',
               existing_type=postgresql.TIMESTAMP(),
               comment='Momento em que o serviço foi acoplado à OS',
               existing_comment='Momento em que o serviço foi acoplado à OS pelo mecânico ou recepcionista',
               existing_nullable=False)
    op.alter_column('os_status_logs', 'operador_id',
               existing_type=sa.UUID(),
               comment='Referência ao operador autenticado',
               existing_comment='Referência ao operador autenticado (Mecânico/Recepcionista/Gerente) que executou o comando',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('os_status_logs', 'operador_id',
               existing_type=sa.UUID(),
               comment='Referência ao operador autenticado (Mecânico/Recepcionista/Gerente) que executou o comando',
               existing_comment='Referência ao operador autenticado',
               existing_nullable=False)
    op.alter_column('os_itens_servico', 'adicionado_em',
               existing_type=postgresql.TIMESTAMP(),
               comment='Momento em que o serviço foi acoplado à OS pelo mecânico ou recepcionista',
               existing_comment='Momento em que o serviço foi acoplado à OS',
               existing_nullable=False)
    op.alter_column('os_itens_servico', 'preco_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço cobrado pela mão de obra no momento da execução (preserva histórico de preços)',
               existing_comment='Preço cobrado pela mão de obra no momento da execução',
               existing_nullable=False)
    op.alter_column('os_itens_peca', 'preco_unitario_aplicado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço de venda unitário congelado no momento de fechamento do orçamento',
               existing_comment='Preço de venda unitário congelado no momento do orçamento',
               existing_nullable=False)
    op.alter_column('os_itens_peca', 'quantidade',
               existing_type=sa.INTEGER(),
               comment='Quantidade física demandada do estoque para o carro',
               existing_comment='Quantidade física demandada do estoque',
               existing_nullable=False)
    # ### end Alembic commands ###
