"""autualizacao ordem servico

Revision ID: 26a48551c78f
Revises: 56d6d46b4339
Create Date: 2026-08-11 21:45:37.551504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a48551c78f'
down_revision: Union[str, Sequence[str], None] = '56d6d46b4339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ordens_servico_cliente_id_fkey'), 'ordens_servico', type_='foreignkey')
    op.create_foreign_key(None, 'ordens_servico', 'clientes', ['cliente_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordens_servico', type_='foreignkey')
    op.create_foreign_key(op.f('ordens_servico_cliente_id_fkey'), 'ordens_servico', 'usuarios', ['cliente_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
