"""servico

Revision ID: 3ce0dd21beae
Revises: 978d04ec3a87
Create Date: 2026-08-09 09:38:19.769973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ce0dd21beae"
down_revision: Union[str, Sequence[str], None] = "978d04ec3a87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servicos_base",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=True),
        sa.Column(
            "preco_mao_de_obra", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("duracao_estimada_minutos", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_servicos_base_nome"), "servicos_base", ["nome"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_servicos_base_nome"), table_name="servicos_base")
    op.drop_table("servicos_base")
    # ### end Alembic commands ###
