"""autualizacao ordem servico

Revision ID: 3d981335c58a
Revises: 12d51f7e6718
Create Date: 2026-08-12 20:10:18.648568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d981335c58a"
down_revision: Union[str, Sequence[str], None] = "12d51f7e6718"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "os_status_logs",
        "operador_id",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="Referência ao operador autenticado",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "os_status_logs",
        "operador_id",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="Referência ao operador autenticado",
    )
    # ### end Alembic commands ###
