"""autualizacao servico

Revision ID: 4addcbafbef5
Revises: 3ce0dd21beae
Create Date: 2026-08-11 20:09:38.144137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4addcbafbef5'
down_revision: Union[str, Sequence[str], None] = '3ce0dd21beae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos_base', sa.Column('permite_servico_expresso', sa.Boolean(), nullable=False, comment='Flag indicando se este serviço é expresso e pula a etapa de diagnóstico físico pelo mecânico'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos_base', 'permite_servico_expresso')
    # ### end Alembic commands ###
