"""generate_veiculo

Revision ID: 4c43d931934a
Revises: 0a2cac9c4204
Create Date: 2026-08-08 18:20:43.743220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c43d931934a"
down_revision: Union[str, Sequence[str], None] = "0a2cac9c4204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "veiculos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("placa", sa.String(length=7), nullable=False),
        sa.Column("marca", sa.String(length=50), nullable=False),
        sa.Column("modelo", sa.String(length=50), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["clientes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_veiculos_placa"), "veiculos", ["placa"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_veiculos_placa"), table_name="veiculos")
    op.drop_table("veiculos")
    # ### end Alembic commands ###
