"""novas colunas

Revision ID: 5608d1bfecaa
Revises: e1f00d465faa
Create Date: 2026-08-05 22:31:58.879862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5608d1bfecaa"
down_revision: Union[str, Sequence[str], None] = "e1f00d465faa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_token_sessions",
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_token_sessions", "revogado_em")
    # ### end Alembic commands ###
