"""autualizacao ordem servico

Revision ID: 56d6d46b4339
Revises: e87c7bcd4423
Create Date: 2026-08-11 20:41:28.574950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56d6d46b4339"
down_revision: Union[str, Sequence[str], None] = "e87c7bcd4423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ordens_servico",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Identificador único global ordenado no tempo (UUIDv7)",
        ),
        sa.Column(
            "cliente_id",
            sa.Uuid(),
            nullable=False,
            comment="Referência ao Cliente associado à OS",
        ),
        sa.Column(
            "veiculo_id",
            sa.UUID(),
            nullable=False,
            comment="Referência ao Veículo em manutenção",
        ),
        sa.Column(
            "mecanico_id",
            sa.Uuid(),
            nullable=True,
            comment="Referência ao Mecânico atribuído para execução/diagnóstico da OS",
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            comment="Status atual da OS dentro da Máquina de Estados",
        ),
        sa.Column(
            "visualizacao_hash",
            sa.Uuid(),
            nullable=False,
            comment="Hash criptográfico opaco utilizado para acompanhamento seguro pelo cliente sem expor o ID sequencial",
        ),
        sa.Column(
            "data_abertura",
            sa.DateTime(),
            nullable=False,
            comment="Data e hora do check-in/abertura da OS na oficina",
        ),
        sa.Column(
            "data_conclusao",
            sa.DateTime(),
            nullable=True,
            comment="Data e hora em que a OS atingiu o status FINALIZADA ou ENTREGUE",
        ),
        sa.Column(
            "data_notificacao_cliente",
            sa.DateTime(),
            nullable=True,
            comment="Data e hora em que o orçamento foi finalizado e enviado para o cliente por WhatsApp",
        ),
        sa.Column(
            "data_resposta_cliente",
            sa.DateTime(),
            nullable=True,
            comment="Data e hora em que o cliente aprovou ou rejeitou o orçamento enviado",
        ),
        sa.Column(
            "tempo_espera_aprovacao_minutos",
            sa.Integer(),
            nullable=True,
            comment="Diferença em minutos entre a notificação e a resposta do cliente (Inércia de aprovação)",
        ),
        sa.Column(
            "leadtime_full_minutos",
            sa.Integer(),
            nullable=True,
            comment="Duração bruta de permanência física do veículo no pátio (Entrada até a Entrega)",
        ),
        sa.Column(
            "leadtime_ativo_minutos",
            sa.Integer(),
            nullable=True,
            comment="Tempo em que a oficina trabalhou de fato (leadtime_full - tempo_espera_aprovacao)",
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["mecanico_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["veiculo_id"], ["veiculos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["visualizacao_hash"], ["usuarios.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("visualizacao_hash"),
    )
    op.create_index(
        op.f("ix_ordens_servico_cliente_id"),
        "ordens_servico",
        ["cliente_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ordens_servico_mecanico_id"),
        "ordens_servico",
        ["mecanico_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ordens_servico_status"), "ordens_servico", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ordens_servico_veiculo_id"),
        "ordens_servico",
        ["veiculo_id"],
        unique=False,
    )
    op.create_table(
        "os_itens_peca",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ordem_servico_id", sa.Uuid(), nullable=False),
        sa.Column("peca_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantidade",
            sa.Integer(),
            nullable=False,
            comment="Quantidade física demandada do estoque para o carro",
        ),
        sa.Column(
            "preco_unitario_aplicado",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Preço de venda unitário congelado no momento de fechamento do orçamento",
        ),
        sa.Column("adicionado_em", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ordem_servico_id"], ["ordens_servico.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["peca_id"], ["pecas_insumos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_os_itens_peca_ordem_servico_id"),
        "os_itens_peca",
        ["ordem_servico_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_os_itens_peca_peca_id"), "os_itens_peca", ["peca_id"], unique=False
    )
    op.create_table(
        "os_itens_servico",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ordem_servico_id", sa.Uuid(), nullable=False),
        sa.Column("servico_base_id", sa.Uuid(), nullable=False),
        sa.Column(
            "preco_aplicado",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Preço cobrado pela mão de obra no momento da execução (preserva histórico de preços)",
        ),
        sa.Column(
            "duracao_minutos",
            sa.Integer(),
            nullable=False,
            comment="Duração real ou estimada em minutos acordada na OS",
        ),
        sa.Column(
            "adicionado_em",
            sa.DateTime(),
            nullable=False,
            comment="Momento em que o serviço foi acoplado à OS pelo mecânico ou recepcionista",
        ),
        sa.ForeignKeyConstraint(
            ["ordem_servico_id"], ["ordens_servico.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["servico_base_id"], ["servicos_base.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_os_itens_servico_ordem_servico_id"),
        "os_itens_servico",
        ["ordem_servico_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_os_itens_servico_servico_base_id"),
        "os_itens_servico",
        ["servico_base_id"],
        unique=False,
    )
    op.create_table(
        "os_status_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ordem_servico_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status_anterior",
            sa.String(length=30),
            nullable=True,
            comment="Status de origem do veículo (Nulo para abertura de OS)",
        ),
        sa.Column(
            "status_novo",
            sa.String(length=30),
            nullable=False,
            comment="Novo status de destino estabelecido",
        ),
        sa.Column(
            "data_transicao",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp preciso da transição física de estado",
        ),
        sa.Column(
            "operador_id",
            sa.Uuid(),
            nullable=False,
            comment="Referência ao operador autenticado (Mecânico/Recepcionista/Gerente) que executou o comando",
        ),
        sa.ForeignKeyConstraint(["operador_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["ordem_servico_id"], ["ordens_servico.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_os_status_logs_ordem_servico_id"),
        "os_status_logs",
        ["ordem_servico_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_os_status_logs_ordem_servico_id"), table_name="os_status_logs"
    )
    op.drop_table("os_status_logs")
    op.drop_index(
        op.f("ix_os_itens_servico_servico_base_id"), table_name="os_itens_servico"
    )
    op.drop_index(
        op.f("ix_os_itens_servico_ordem_servico_id"), table_name="os_itens_servico"
    )
    op.drop_table("os_itens_servico")
    op.drop_index(op.f("ix_os_itens_peca_peca_id"), table_name="os_itens_peca")
    op.drop_index(op.f("ix_os_itens_peca_ordem_servico_id"), table_name="os_itens_peca")
    op.drop_table("os_itens_peca")
    op.drop_index(op.f("ix_ordens_servico_veiculo_id"), table_name="ordens_servico")
    op.drop_index(op.f("ix_ordens_servico_status"), table_name="ordens_servico")
    op.drop_index(op.f("ix_ordens_servico_mecanico_id"), table_name="ordens_servico")
    op.drop_index(op.f("ix_ordens_servico_cliente_id"), table_name="ordens_servico")
    op.drop_table("ordens_servico")
    # ### end Alembic commands ###
