"""estoque

Revision ID: 978d04ec3a87
Revises: 4c43d931934a
Create Date: 2026-08-08 19:53:07.247823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "978d04ec3a87"
down_revision: Union[str, Sequence[str], None] = "4c43d931934a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pecas_insumos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=True),
        sa.Column("quantidade_em_estoque", sa.Integer(), nullable=False),
        sa.Column("preco_venda", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("preco_custo", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("limite_minimo", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pecas_insumos_nome"), "pecas_insumos", ["nome"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pecas_insumos_nome"), table_name="pecas_insumos")
    op.drop_table("pecas_insumos")
    # ### end Alembic commands ###
