"""ajustar_novamente_tabela_clientes

Revision ID: bda9615c23ff
Revises: 0e50ce2cabc8
Create Date: 2026-07-30 08:58:02.892770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bda9615c23ff"
down_revision: Union[str, Sequence[str], None] = "0e50ce2cabc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clientes", sa.Column("telefone", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "clientes", sa.Column("cpf_cnpj", sa.String(length=14), nullable=False)
    )
    op.add_column(
        "clientes",
        sa.Column(
            "tipo_pessoa",
            sa.Enum("FISICA", "JURIDICA", name="tipopessoa", native_enum=False),
            nullable=False,
        ),
    )
    op.add_column(
        "clientes",
        sa.Column(
            "role",
            sa.Enum(
                "CLIENTE",
                "RECEPCIONISTA",
                "MECANICO",
                "ESTOQUISTA",
                "GERENTE",
                name="role",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_clientes_cpf"), table_name="clientes")
    op.create_index(op.f("ix_clientes_cpf_cnpj"), "clientes", ["cpf_cnpj"], unique=True)
    op.drop_column("clientes", "cpf")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clientes",
        sa.Column("cpf", sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_clientes_cpf_cnpj"), table_name="clientes")
    op.create_index(op.f("ix_clientes_cpf"), "clientes", ["cpf"], unique=True)
    op.drop_column("clientes", "role")
    op.drop_column("clientes", "tipo_pessoa")
    op.drop_column("clientes", "cpf_cnpj")
    op.drop_column("clientes", "telefone")
    # ### end Alembic commands ###
