"""criar_tabelas_autenticacao_e_vinculo_cliente

Revision ID: e1f00d465faa
Revises: bda9615c23ff
Create Date: 2026-07-30 22:32:31.523129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1f00d465faa"
down_revision: Union[str, Sequence[str], None] = "bda9615c23ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CLIENTE",
                "RECEPCIONISTA",
                "MECANICO",
                "ESTOQUISTA",
                "GERENTE",
                name="role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_table(
        "refresh_token_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("revogado", sa.Boolean(), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("substituido_por_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_sessions_token_hash"),
        "refresh_token_sessions",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_token_sessions_usuario_id"),
        "refresh_token_sessions",
        ["usuario_id"],
        unique=False,
    )
    op.add_column("clientes", sa.Column("usuario_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "clientes", "usuarios", ["usuario_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clientes", type_="foreignkey")
    op.drop_column("clientes", "usuario_id")
    op.drop_index(
        op.f("ix_refresh_token_sessions_usuario_id"),
        table_name="refresh_token_sessions",
    )
    op.drop_index(
        op.f("ix_refresh_token_sessions_token_hash"),
        table_name="refresh_token_sessions",
    )
    op.drop_table("refresh_token_sessions")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    # ### end Alembic commands ###
