"""autualizacao ordem servico

Revision ID: e87c7bcd4423
Revises: dc3f6ac971ed
Create Date: 2026-08-11 20:37:14.819928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87c7bcd4423'
down_revision: Union[str, Sequence[str], None] = 'dc3f6ac971ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
